name: Build, Test, Generate Allure Report, and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Build and test with Maven
      run: mvn clean install

    - name: Generate Allure report
      run: mvn allure:report

    - name: Serve Allure report
      run: mvn allure:serve

    - name: Upload Allure results
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: target/allure-results

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: target/allure-report

  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Checkout code for deploy
        uses: actions/checkout@v2
        with:
          ref: gh-pages # Puedes especificar aquí la rama a la que deseas realizar el despliegue

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.SELENIUM }}
          publish_dir: ./target/allure-report
          publish_branch: gh-pages
