name: Build, Test, Generate Allure Report, and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test with Maven
      run: mvn clean install

    - name: Generate Allure report
      run: mvn allure:report
      working-directory: ./target

    - name: Upload Allure results
      uses: actions/upload-artifact@v2
      with:
        name: allure-results
        path: ./results/allure-results

    - name: Upload Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: ./allure-report

  deploy-to-gh-pages:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code for deploy
      uses: actions/checkout@v2
      with:
        ref: gh-pages # Puedes especificar aquí la rama a la que deseas realizar el despliegue

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.SELENIUM }}
        publish_dir: ./allure-report
        publish_branch: gh-pages

    - name: Show Allure report URL
      run: |
        echo "Allure Report URL: https://{{ github.repository }}/gh-pages/"

