name: Build, Test, Generate Allure Report, and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test with Maven
      run: mvn clean install

    - name: Generate Allure report
      run: |
        # Genera el informe de Allure en la ruta especificada
        mvn allure:report -Dallure.results.directory=target/allure-results

    - name: Configure Git identity
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Commit changes to gh-pages
      run: |
        # Crea una rama gh-pages o cambia a ella si ya existe
        git checkout -B gh-pages
        
        # Copia el informe de Allure a la raíz del repositorio
        cp -r target/allure-report/* .
        
        # Agrega y confirma los cambios
        git add .
        git commit -m "Deploy Allure report to gh-pages" || true
        
        # Sincroniza con la rama gh-pages remota
        git pull origin gh-pages --rebase
        
        # Empuja los cambios a la rama gh-pages
        git push origin gh-pages

    - name: Show Allure report URL
      run: |
        # Muestra la URL del informe de Allure
        echo "Allure Report URL: https://Victor-Jenkins.github.io/MASTER_Selenium_Allure/"
