name: Build, Test, Commit Main to gh-pages, Generate Allure Report, and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test with Maven
      run: mvn clean install

    - name: Configure Git identity
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

    - name: Create and switch to gh-pages branch (based on main)
      run: |
        git checkout main
        git checkout -b gh-pages
        git push origin gh-pages

    - name: Generate Allure report
      run: mvn allure:report

    - name: Move Allure report files
      run: mv target/results/allure-report/* .

    - name: Commit and push Allure report to gh-pages
      run: |
        git add .
        git commit -m "Deploy Allure report to gh-pages"
        git push origin gh-pages

    - name: Show Allure report URL
      run: |
        echo "Allure Report URL: https://Victor-Jenkins.github.io/MASTER_Selenium_Allure/allure-report/"

