name: Compilar, Probar, Generar Informe Allure y Desplegar en gh-pages

on:
  push:
    branches:
      - main

jobs:
  compilar-y-desplegar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código
      uses: actions/checkout@v2

    - name: Compilar y probar con Maven
      run: mvn clean install

    - name: Generar informe Allure
      run: mvn allure:report

    - name: Configurar la identidad de Git
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    
    - name: Seleccionar o crear la rama gh-pages
      run: |
        git checkout -B gh-pages origin/gh-pages || git checkout --orphan gh-pages
    
    - name: Eliminar archivos existentes del informe Allure
      run: |
        git rm -rf .
    
    - name: Mover archivos del informe Allure
      run: |
        mv target/results/allure-report/* .

    - name: Confirmar y enviar el informe Allure a gh-pages
      run: |
        git add .
        git commit -m "Desplegar informe Allure en gh-pages"
        git push origin gh-pages
    
    - name: Mostrar la URL del informe Allure
      run: |
        echo "URL del informe Allure: https://Victor-Jenkins.github.io/MASTER_Selenium_Allure/allure-report/"
