name: Build, Test, Generate Allure Report, and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test with Maven
      run: mvn clean install

    - name: Generate Allure report
      run: mvn allure:report

    - name: Deploy Allure report to gh-pages
      run: |
        git checkout gh-pages
        git rm -rf .
        cp -r target/allure-report/* .
        git add .
        git commit -m "Deploy Allure report to gh-pages"
        git push origin gh-pages

    - name: Start Allure serve on gh-pages
      run: |
        git checkout gh-pages
        allure serve

