name: Build, Test, Generate Allure Report, and Deploy to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test with Maven
      run: mvn clean install

    - name: Generate Allure report
      run: mvn allure:report

    - name: Push to gh-pages branch
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        git checkout gh-pages
        mv target/results/allure-report/* .
        git add .
        git commit -m "Deploy Allure report to gh-pages"
        git push origin gh-pages

    - name: Show Allure report URL
      run: |
        echo "Allure Report URL: https://Victor-Jenkins.github.io/MASTER_Selenium_Allure/allure-report/"

